### 1. 회원적립금 지급
POST {{host}}/v1/publish HTTP/1.1
Content-Type: application/json

{
  "memberNumber" : 888888888,
  "point" : 100,
  "historyType" : 1,
  "payment" : false,
  "settle" : false,
  "expireDate" : "2030-12-31T23:59:59Z",
  "memo" : "발급사유(내부)",
  "detail" : "발급사유(고객용)",
  "actionMemberNumber" : 0,
  "hidden" : false
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### 2. 가용 포인트 조회
GET {{host}}/v1/available/888888888 HTTP/1.1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### 3. 포인트 예약
POST http://127.0.0.1:8080/v2/reserve
Content-Type: application/json

{
  "memberNumber" : 888888888,
  "point" : 100,
  "historyType" : 1,
  "payment" : false,
  "settle" : false,
  "startDate" : "2021-11-15T19:00:00Z",
  "expireDate" : "2030-12-31T23:59:59Z",
  "memo" : "발급사유(내부)",
  "detail" : "발급사유(고객용)",
  "actionMemberNumber" : 0,
  "hidden" : false
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### 4. 가용 포인트 조회
GET {{host}}/v1/available/888888888 HTTP/1.1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
